/**
 * Savo Intelligence, the answer engine behind "Ask Savo Anything".
 *
 * Runs server-side (app/api/chat) so answers are generated by an agent on the
 * backend and presented as Savo Technologies' own assistant. The rule-based
 * responder below is the deterministic v1: concise, quotable, fact-checked
 * against the site's own claims. Swap `respond()` with an LLM call (any
 * provider) when the production integration lands, the branding contract in
 * the UI never changes and the provider is never named to the visitor.
 */

export type SavoAnswer = { answer: string; followUps: string[] };

const KB: { match: RegExp; entry: SavoAnswer }[] = [
  {
    match: /(price|pricing|cost|estimate|budget|charge|rate|how much|₹|rupee)/i,
    entry: {
      answer:
        "A focused web or mobile build typically lands between ₹2.5 to 8 lakh, a custom AI agent deployment between ₹6 to 18 lakh, and enterprise platforms scale from ₹25 lakh upward. Use the Instant Estimator on this page for a tailored INR range in seconds, a free discovery call then converts it into a fixed, itemized quote.",
      followUps: ["How does the estimation process work?", "Can I hire developers instead?"],
    },
  },
  {
    match: /(service|offer|do you (do|build|provide)|what.*(offer|provide)|capabilit)/i,
    entry: {
      answer:
        "Savo Technologies offers AI agent development, custom software, mobile apps, web development, cloud & DevOps, data & analytics, UI/UX, digital marketing & SEO, QA, IT consulting, cybersecurity and product engineering, one accountable team for the full spectrum.",
      followUps: ["Tell me about your AI agents", "What industries do you serve?"],
    },
  },
  {
    match: /(agent|bot|chatbot|llm|ai |genai|artificial)/i,
    entry: {
      answer:
        "Our flagship offering. Six production ready AI agents (SalesBot, SupportAgent, RecruitAI, InsightAgent, ContentAgent and OpsAgent) cover sales, support, HR, analytics, content and IT operations. Each is trained on your data, integrated with your stack, and deployed in a 2 to 4 week sprint with human handoff and audit logs.",
      followUps: ["How are agents customized?", "How much does an AI agent cost?"],
    },
  },
  {
    match: /(region|countr|india|usa|america|saudi|gcc|gulf|uae|uk|britain|australia|global|where)/i,
    entry: {
      answer:
        "India is our home market and engineering HQ. We actively serve the USA, Saudi Arabia & the GCC, the United Kingdom and Australia: 25+ countries over ten years, with delivery pods that overlap your working hours.",
      followUps: ["How do timezones work for delivery?", "How do I get started?"],
    },
  },
  {
    match: /(process|engage|workflow|agile|sprint|methodolog|how.*work|develop)/i,
    entry: {
      answer:
        "Every project runs through discover, design, build, launch and scale in two week agile sprints with a demo every Friday. You watch progress live in the client portal: milestones, deliverables, invoices and direct chat with your dedicated team.",
      followUps: ["How can I track my project?", "What is your pricing model?"],
    },
  },
  {
    match: /(secur|gdpr|privacy|compliance|iso|nda|data|safe)/i,
    entry: {
      answer:
        "Security is engineered in, not asserted: GDPR aligned and ISO compliant processes, NDA first engagements, encryption in transit and at rest, role-based access, and audit logs on every AI action. Your data never trains public models.",
      followUps: ["How do AI agents handle our data?", "How do I get started?"],
    },
  },
  {
    match: /(hire|dedicated|resource|team|staff|developer|engineer|full.?time|part.?time|hourly|freelanc|upwork|indore)/i,
    entry: {
      answer:
        "Yes, hire dedicated frontend, backend, full stack, mobile, AI/ML, DevOps and QA engineers, plus designers and project managers. Full time, part-time or hourly; junior to senior. It is the quality clients look for in top freelancers or top Upwork developers in India, with agency accountability: contracts, NDAs, dedicated teams and transparent monthly INR rates from ₹60,000/month, typically 40 to 60% below equivalent US/UK/Gulf rates. Delivery from Indore and Ahmedabad for clients in the USA, Saudi Arabia, Dubai and the GCC, the UK and Australia.",
      followUps: ["What are your developer rates?", "How quickly can a team start?"],
    },
  },
  {
    match: /(portal|track|status|milestone|invoice|dashboard)/i,
    entry: {
      answer:
        "Every engagement includes a secure client portal: live milestone tracking, deliverables and invoices in one auditable place, and direct messaging with your dedicated team, with answers in hours, not days.",
      followUps: ["What is your development process?", "How do I get started?"],
    },
  },
  {
    match: /(industr|healthcare|fintech|bank|ecommerce|retail|real estate|logistic|education|travel|manufactur|government|energy|sector)/i,
    entry: {
      answer:
        "Ten sectors over a decade: healthcare, fintech & banking, e-commerce & retail, real estate, logistics & supply chain, education, travel & hospitality, manufacturing & Industry 4.0, government, and energy & utilities, with particular depth in the Gulf's energy economy.",
      followUps: ["Do you have case studies?", "What services do you offer?"],
    },
  },
  {
    match: /(case stud|portfolio|example|work|project.*(done|built)|client)/i,
    entry: {
      answer:
        "650+ projects across web, mobile and AI, from MediBridge Health's patient portal to GulfPay's GCC wallet and a telecom support agent resolving 96% of tier 1 chats in Arabic and English. See the Featured Work section for a curated selection.",
      followUps: ["Tell me about your AI agents", "How do I get started?"],
    },
  },
  {
    match: /(start|begin|kick.?off|onboard|contact|talk|call|meeting|demo|book)/i,
    entry: {
      answer:
        "Use the Instant Estimator or click Start Your Project, share a few details, and a senior engineer replies within one business day with a plan, a team and a number. For an agent demo, pick any agent in the Meet Our AI Agents section.",
      followUps: ["How much does a project cost?", "Which regions do you serve?"],
    },
  },
  {
    match: /(time|long|fast|quick|deadline|urgent|deliver)/i,
    entry: {
      answer:
        "A typical build runs 2 to 3 months; urgent scopes compress to 4 to 8 weeks; enterprise platforms run 6 to 12 months in phases. Dedicated hired teams can start within two weeks of kickoff.",
      followUps: ["What is your pricing model?", "How do I get started?"],
    },
  },
];

const FALLBACK: SavoAnswer = {
  answer:
    "Good question. Here is the short version: Savo Technologies is a 10-year global company offering AI agent development, web and mobile development, and full spectrum software services across India, the USA, Saudi Arabia & GCC, the UK and Australia. Ask me about services, pricing, AI agents, hiring developers, industries or process, or use the Instant Estimator below for a tailored INR range.",
  followUps: ["What services do you offer?", "How much does an app cost?"],
};

export function respond(question: string): SavoAnswer {
  const hit = KB.find((k) => k.match.test(question));
  return hit ? hit.entry : FALLBACK;
}
